namespace Dust.HUD
{
	public enum TextBoxType
	{
		Null = -1,
		Dialogue = 0,
		IfEvent = 1,
		IfSideEvent = 2,
		IfQuestActive = 3,
		IfQuestCanComplete = 4,
		IfQuestCompleted = 5,
		IfNoteFound = 6,
		IfRandom = 7,
		IfConversation = 8,
		IfConversationGreater = 9,
		IfQuestStage = 10,
		InitCommand = 50,
		InitEvent = 51,
		InitSideEvent = 52,
		SetConv = 53,
		Skippable = 54,
		UnSkippable = 55,
		InitShop = 56,
		InitQuest = 57,
		SetQuestStage = 58,
		CompleteQuest = 59,
		AddNote = 60,
		SetMinConv = 61,
		SetCamera = 62,
		FaceCharacter = 63,
		FaceLocation = 64,
		Shake = 65,
		PlaySound = 66,
		AddEquip = 67,
		AddBluePrint = 68,
		AddMaterial = 69,
		GlobalStart = 70,
		Blank = 71,
		RevealMap = 72,
		SetQuestSideStage = 73,
		SetEvent = 74,
		SetSideEvent = 75,
		BlurOn = 76,
		SetAnim = 77,
		AddGold = 78,
		AddXP = 79
	}
}
